"""
Build sql/junction_viridian_counts.sql from Jim's per-sample CSVs.

Column A = sample id, B = Viridian variant call, C = Viridian primer call.
'.' in B means no variant call. Counts only (no percentages).
Also writes a Delta (all) rollup per group.
"""
from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_DIR = ROOT / "_incoming" / "jim-kelley"
OUT_SQL = ROOT / "sql" / "junction_viridian_counts.sql"

FILE_META = [
    {
        "match": "NJ-all_bbmap",
        "code": "NJ",
        "name": "NJ MiSeq",
        "location": "New Jersey",
        "continent": "N America",
        "instrument": "MiSeq",
    },
    {
        "match": "PRJNA656534-NM",
        "code": "NM",
        "name": "NM MiSeq",
        "location": "New Mexico",
        "continent": "N America",
        "instrument": "MiSeq",
    },
]


def sql_str(value) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def find_csv(match: str) -> Path:
    hits = list(CSV_DIR.glob("*" + match + "*.csv"))
    if not hits:
        raise SystemExit("Missing CSV matching " + match + " in " + str(CSV_DIR))
    return hits[0]


def family_key(variant: str) -> str | None:
    name = variant.strip()
    if name in ("", "."):
        return None
    token = name.split()[0]
    token = token.split("(")[0]
    if token.lower() == "delta":
        return "Delta (all)"
    return None


def main() -> None:
    groups = []
    variant_counts: dict[tuple[str, str], int] = defaultdict(int)
    pair_counts: dict[tuple[str, str, str], int] = defaultdict(int)

    for i, meta in enumerate(FILE_META, start=1):
        path = find_csv(meta["match"])
        meta = dict(meta)
        meta["id"] = i
        meta["source_file"] = path.name
        groups.append(meta)
        with path.open(newline="", encoding="utf-8", errors="replace") as fh:
            for row in csv.reader(fh):
                if len(row) < 3:
                    continue
                variant = row[1].strip()
                primer = row[2].strip()
                if variant == "":
                    variant = "."
                variant_counts[(meta["code"], variant)] += 1
                pair_counts[(meta["code"], variant, primer)] += 1
                fam = family_key(variant)
                if fam:
                    variant_counts[(meta["code"], fam)] += 1

    lines = [
        "-- Viridian per-sample counts (NJ and NM examples).",
        "-- Generated by scripts/import_viridian_counts.py",
        "-- Reverse: sql/junction_query_drop.sql",
        "",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS=0;",
        "DROP TABLE IF EXISTS `junction_viridian_pair`;",
        "DROP TABLE IF EXISTS `junction_viridian_variant`;",
        "DROP TABLE IF EXISTS `junction_viridian_group`;",
        "SET FOREIGN_KEY_CHECKS=1;",
        "",
        "CREATE TABLE `junction_viridian_group` (",
        "  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,",
        "  `code` varchar(16) NOT NULL,",
        "  `name` varchar(128) NOT NULL,",
        "  `location_name` varchar(128) DEFAULT NULL,",
        "  `continent` varchar(32) DEFAULT NULL,",
        "  `instrument` varchar(64) DEFAULT NULL,",
        "  `source_file` varchar(255) NOT NULL,",
        "  PRIMARY KEY (`id`),",
        "  UNIQUE KEY `uq_jvg_code` (`code`)",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        "",
        "CREATE TABLE `junction_viridian_variant` (",
        "  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,",
        "  `group_id` int(10) UNSIGNED NOT NULL,",
        "  `variant_name` varchar(255) NOT NULL,",
        "  `sample_count` int(11) NOT NULL,",
        "  `is_rollup` tinyint(1) NOT NULL DEFAULT 0,",
        "  PRIMARY KEY (`id`),",
        "  KEY `idx_jvv_group` (`group_id`),",
        "  CONSTRAINT `fk_jvv_group` FOREIGN KEY (`group_id`) REFERENCES `junction_viridian_group` (`id`) ON DELETE CASCADE",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        "",
        "CREATE TABLE `junction_viridian_pair` (",
        "  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,",
        "  `group_id` int(10) UNSIGNED NOT NULL,",
        "  `variant_name` varchar(255) NOT NULL,",
        "  `primer_name` varchar(128) NOT NULL,",
        "  `sample_count` int(11) NOT NULL,",
        "  PRIMARY KEY (`id`),",
        "  KEY `idx_jvp_group` (`group_id`),",
        "  CONSTRAINT `fk_jvp_group` FOREIGN KEY (`group_id`) REFERENCES `junction_viridian_group` (`id`) ON DELETE CASCADE",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        "",
        "INSERT INTO `junction_viridian_group`",
        "  (`id`,`code`,`name`,`location_name`,`continent`,`instrument`,`source_file`)",
        "VALUES",
    ]
    g_rows = []
    for g in groups:
        g_rows.append(
            "  ({id},{code},{name},{loc},{cont},{inst},{src})".format(
                id=g["id"],
                code=sql_str(g["code"]),
                name=sql_str(g["name"]),
                loc=sql_str(g["location"]),
                cont=sql_str(g["continent"]),
                inst=sql_str(g["instrument"]),
                src=sql_str(g["source_file"]),
            )
        )
    lines.append(",\n".join(g_rows) + ";")
    lines.append("")

    code_to_id = {g["code"]: g["id"] for g in groups}
    v_rows = []
    vid = 0
    for (code, variant), n in sorted(variant_counts.items(), key=lambda x: (x[0][0], x[0][1] != "Delta (all)", x[0][1] == ".", x[0][1])):
        vid += 1
        is_rollup = 1 if variant.endswith("(all)") else 0
        v_rows.append(
            "  ({id},{gid},{vname},{n},{roll})".format(
                id=vid,
                gid=code_to_id[code],
                vname=sql_str(variant),
                n=int(n),
                roll=is_rollup,
            )
        )
    lines.append("INSERT INTO `junction_viridian_variant`")
    lines.append("  (`id`,`group_id`,`variant_name`,`sample_count`,`is_rollup`)")
    lines.append("VALUES")
    lines.append(",\n".join(v_rows) + ";")
    lines.append("")

    p_rows = []
    pid = 0
    for (code, variant, primer), n in sorted(pair_counts.items()):
        pid += 1
        p_rows.append(
            "  ({id},{gid},{vname},{pname},{n})".format(
                id=pid,
                gid=code_to_id[code],
                vname=sql_str(variant),
                pname=sql_str(primer),
                n=int(n),
            )
        )
    lines.append("INSERT INTO `junction_viridian_pair`")
    lines.append("  (`id`,`group_id`,`variant_name`,`primer_name`,`sample_count`)")
    lines.append("VALUES")
    lines.append(",\n".join(p_rows) + ";")
    lines.append("")

    OUT_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        "Wrote {out} groups={g} variant_rows={v} pair_rows={p}".format(
            out=OUT_SQL, g=len(groups), v=len(v_rows), p=len(p_rows)
        )
    )


if __name__ == "__main__":
    main()
