"""Build sql/snv_pango_marker.sql from Jim Kelley's pango designation workbook.

Rule (Jim, 2026-09-09): Column C = coordinate, D = ref, E = alt, I = ratio.
If len(ref) == 1 and len(alt) == 1 and ratio < 0.2, Column A (lineage) is
attached to that SNV.

Do not parse xlsx in PHP. Re-run this script if the spreadsheet changes.
"""
from __future__ import annotations

from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
INBOX = ROOT / "_incoming" / "jim-kelley"
PACKET_FILES = INBOX / "2026-09-09_pango-snv-lineages" / "files"
SOURCE_NAME = "pango-designation-markers-v1.9-calc-sort.xlsx"
OUT_SQL = ROOT / "sql" / "snv_pango_marker.sql"
OUT_DROP_SQL = ROOT / "sql" / "snv_pango_marker_drop.sql"

RATIO_LT = 0.2


def sql_str(value: object | None) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def sql_num(value: object | None) -> str:
    if value is None:
        return "NULL"
    return repr(float(value))


def find_xlsx() -> Path:
    named = (
        PACKET_FILES / SOURCE_NAME,
        INBOX / SOURCE_NAME,
    )
    for path in named:
        if path.is_file():
            return path
    hits = sorted(INBOX.glob("**/" + SOURCE_NAME))
    if hits:
        return hits[0]
    raise SystemExit("Missing " + SOURCE_NAME + " under " + str(INBOX))


def cell_text(value: object | None) -> str:
    if value is None:
        return ""
    return str(value).strip()


def parse_ratio(value: object | None) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def is_single_base_snv(ref: str, alt: str) -> bool:
    return len(ref) == 1 and len(alt) == 1


def qualifies_snv_row(ref: str, alt: str, ratio: float | None, threshold: float = RATIO_LT) -> bool:
    """True when Jim's rule attaches Column A to the SNV."""
    if not is_single_base_snv(ref, alt):
        return False
    if ratio is None:
        return False
    return ratio < threshold


def iter_qualifying_rows(path: Path) -> list[dict[str, object]]:
    wb = load_workbook(path, read_only=True, data_only=True)
    ws = wb[wb.sheetnames[0]]
    out: list[dict[str, object]] = []
    seen: dict[tuple[str, int, str, str], int] = {}

    for source_row, raw in enumerate(ws.iter_rows(min_row=2, max_col=9, values_only=True), start=2):
        lineage = cell_text(raw[0] if len(raw) > 0 else None)
        chrom = cell_text(raw[1] if len(raw) > 1 else None)
        pos_raw = raw[2] if len(raw) > 2 else None
        ref = cell_text(raw[3] if len(raw) > 3 else None).upper()
        alt = cell_text(raw[4] if len(raw) > 4 else None).upper()
        adref = raw[5] if len(raw) > 5 else None
        adalt = raw[6] if len(raw) > 6 else None
        dp = raw[7] if len(raw) > 7 else None
        ratio = parse_ratio(raw[8] if len(raw) > 8 else None)

        if lineage == "" or pos_raw is None:
            continue
        try:
            coordinate = int(pos_raw)
        except (TypeError, ValueError):
            continue
        if not qualifies_snv_row(ref, alt, ratio):
            continue

        key = (lineage, coordinate, ref, alt)
        row = {
            "lineage": lineage,
            "chrom": chrom or None,
            "coordinate": coordinate,
            "reference": ref,
            "alternate": alt,
            "adref": int(adref) if isinstance(adref, (int, float)) else None,
            "adalt": int(adalt) if isinstance(adalt, (int, float)) else None,
            "dp": int(dp) if isinstance(dp, (int, float)) else None,
            "ratio": ratio,
            "source_row": source_row,
        }
        prev = seen.get(key)
        if prev is None:
            seen[key] = len(out)
            out.append(row)
            continue
        # Keep the lower ratio if the same lineage/SNV appears twice.
        if ratio is not None and (out[prev]["ratio"] is None or ratio < float(out[prev]["ratio"])):
            out[prev] = row

    return out


def write_drop_sql() -> None:
    OUT_DROP_SQL.write_text(
        "-- Reverse sql/snv_pango_marker.sql without touching the mutations table.\n"
        "SET FOREIGN_KEY_CHECKS=0;\n"
        "DROP TABLE IF EXISTS `snv_pango_marker`;\n"
        "SET FOREIGN_KEY_CHECKS=1;\n",
        encoding="utf-8",
    )


def write_sql(path: Path, rows: list[dict[str, object]]) -> None:
    lines = [
        "-- Pango lineage names attached to SNVs (Jim Kelley designation markers v1.9).",
        "-- Generated by scripts/import_pango_snv_markers.py",
        "-- Source: " + path.name,
        "-- Rule: len(ref)=1 AND len(alt)=1 AND ratio < 0.2; Column A is the lineage.",
        "-- Reverse with sql/snv_pango_marker_drop.sql",
        "",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS=0;",
        "DROP TABLE IF EXISTS `snv_pango_marker`;",
        "SET FOREIGN_KEY_CHECKS=1;",
        "",
        "CREATE TABLE `snv_pango_marker` (",
        "  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,",
        "  `lineage` varchar(64) NOT NULL,",
        "  `chrom` varchar(32) DEFAULT NULL,",
        "  `coordinate` int(11) NOT NULL,",
        "  `reference` char(1) NOT NULL,",
        "  `alternate` char(1) NOT NULL,",
        "  `adref` int(11) DEFAULT NULL,",
        "  `adalt` int(11) DEFAULT NULL,",
        "  `dp` int(11) DEFAULT NULL,",
        "  `ratio` double DEFAULT NULL,",
        "  `source_row` int(11) NOT NULL,",
        "  PRIMARY KEY (`id`),",
        "  UNIQUE KEY `uq_snv_pango` (`coordinate`,`reference`,`alternate`,`lineage`),",
        "  KEY `idx_snv_pango_snv` (`coordinate`,`reference`,`alternate`)",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
        "",
    ]
    if rows:
        lines.append(
            "INSERT INTO `snv_pango_marker` "
            "(`id`,`lineage`,`chrom`,`coordinate`,`reference`,`alternate`,`adref`,`adalt`,`dp`,`ratio`,`source_row`)"
        )
        lines.append("VALUES")
        value_lines = []
        for i, row in enumerate(rows, start=1):
            comma = "," if i < len(rows) else ";"
            value_lines.append(
                "  ({id},{lineage},{chrom},{coord},{ref},{alt},{adref},{adalt},{dp},{ratio},{src}){comma}".format(
                    id=i,
                    lineage=sql_str(row["lineage"]),
                    chrom=sql_str(row["chrom"]),
                    coord=int(row["coordinate"]),
                    ref=sql_str(row["reference"]),
                    alt=sql_str(row["alternate"]),
                    adref="NULL" if row["adref"] is None else int(row["adref"]),
                    adalt="NULL" if row["adalt"] is None else int(row["adalt"]),
                    dp="NULL" if row["dp"] is None else int(row["dp"]),
                    ratio=sql_num(row["ratio"]),
                    src=int(row["source_row"]),
                    comma=comma,
                )
            )
        lines.extend(value_lines)
        lines.append("")

    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    path = find_xlsx()
    rows = iter_qualifying_rows(path)
    snvs = {(r["coordinate"], r["reference"], r["alternate"]) for r in rows}
    write_drop_sql()
    write_sql(path, rows)
    print("source", path)
    print("qualifying_rows", len(rows))
    print("distinct_snvs", len(snvs))
    print("wrote", OUT_SQL)
    print("wrote", OUT_DROP_SQL)


if __name__ == "__main__":
    main()
