-- Viridian per-sample counts (NJ and NM examples).
-- Generated by scripts/import_viridian_counts.py
-- Reverse: sql/junction_query_drop.sql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `junction_viridian_pair`;
DROP TABLE IF EXISTS `junction_viridian_variant`;
DROP TABLE IF EXISTS `junction_viridian_group`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `junction_viridian_group` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` varchar(16) NOT NULL,
  `name` varchar(128) NOT NULL,
  `location_name` varchar(128) DEFAULT NULL,
  `continent` varchar(32) DEFAULT NULL,
  `instrument` varchar(64) DEFAULT NULL,
  `source_file` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_jvg_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `junction_viridian_variant` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` int(10) UNSIGNED NOT NULL,
  `variant_name` varchar(255) NOT NULL,
  `sample_count` int(11) NOT NULL,
  `is_rollup` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_jvv_group` (`group_id`),
  CONSTRAINT `fk_jvv_group` FOREIGN KEY (`group_id`) REFERENCES `junction_viridian_group` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `junction_viridian_pair` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` int(10) UNSIGNED NOT NULL,
  `variant_name` varchar(255) NOT NULL,
  `primer_name` varchar(128) NOT NULL,
  `sample_count` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_jvp_group` (`group_id`),
  CONSTRAINT `fk_jvp_group` FOREIGN KEY (`group_id`) REFERENCES `junction_viridian_group` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `junction_viridian_group`
  (`id`,`code`,`name`,`location_name`,`continent`,`instrument`,`source_file`)
VALUES
  (1,'NJ','NJ MiSeq','New Jersey','N America','MiSeq','NJ-all_bbmap.txt-bbmap-sorted.bam-mapped_reads-C8-vir_pass-info-all-var_primer_col.csv'),
  (2,'NM','NM MiSeq','New Mexico','N America','MiSeq','PRJNA656534-NM-bbmap.txt-bbmap-sorted.bam-mapped_reads-C8-vir_pass-info-var_primer_col.csv');

INSERT INTO `junction_viridian_variant`
  (`id`,`group_id`,`variant_name`,`sample_count`,`is_rollup`)
VALUES
  (1,1,'Delta (all)',2355,1),
  (2,1,'Alpha (B.1.1.7-like)',497,0),
  (3,1,'B.1.1.318-like',2,0),
  (4,1,'B.1.1.7-like+E484K',1,0),
  (5,1,'Beta (B.1.351-like)',3,0),
  (6,1,'Delta (AY.4-like)',24,0),
  (7,1,'Delta (AY.4.2-like)',1,0),
  (8,1,'Delta (B.1.617.2-like)',2328,0),
  (9,1,'Delta (B.1.617.2-like) +K417N',2,0),
  (10,1,'Epsilon (B.1.427-like)',2,0),
  (11,1,'Epsilon (B.1.429-like)',4,0),
  (12,1,'Eta (B.1.525-like)',2,0),
  (13,1,'Gamma (P.1-like)',58,0),
  (14,1,'Iota (B.1.526-like)',230,0),
  (15,1,'Lambda (C.37-like)',7,0),
  (16,1,'Mu (B.1.621-like)',6,0),
  (17,1,'Omicron (BA.1-like)',629,0),
  (18,1,'Omicron (BA.2-like)',463,0),
  (19,1,'Omicron (BA.4-like)',83,0),
  (20,1,'Omicron (BA.5-like)',590,0),
  (21,1,'Omicron (XBB-like)',11,0),
  (22,1,'Omicron (XBB.1-like)',95,0),
  (23,1,'Omicron (XBB.1.16-like)',14,0),
  (24,1,'Omicron (XBB.1.5-like)',188,0),
  (25,1,'Omicron (XE-like)',1,0),
  (26,1,'Zeta (P.2-like)',1,0),
  (27,1,'.',155,0),
  (28,2,'Delta (all)',834,1),
  (29,2,'Alpha (B.1.1.7-like)',328,0),
  (30,2,'Delta (B.1.617.2-like)',832,0),
  (31,2,'Delta (B.1.617.2-like) +K417N',2,0),
  (32,2,'Epsilon (B.1.427-like)',3,0),
  (33,2,'Epsilon (B.1.429-like)',24,0),
  (34,2,'Omicron (BA.1-like)',269,0),
  (35,2,'Omicron (BA.2-like)',680,0),
  (36,2,'Omicron (BA.4-like)',30,0),
  (37,2,'Omicron (BA.5-like)',354,0),
  (38,2,'Omicron (XBB-like)',3,0),
  (39,2,'Omicron (XBB.1-like)',27,0),
  (40,2,'Omicron (XBB.1.16-like)',7,0),
  (41,2,'Omicron (XBB.1.5-like)',8,0),
  (42,2,'.',143,0);

INSERT INTO `junction_viridian_pair`
  (`id`,`group_id`,`variant_name`,`primer_name`,`sample_count`)
VALUES
  (1,1,'.','V3',155),
  (2,1,'Alpha (B.1.1.7-like)','V3',497),
  (3,1,'B.1.1.318-like','V3',2),
  (4,1,'B.1.1.7-like+E484K','V3',1),
  (5,1,'Beta (B.1.351-like)','V3',3),
  (6,1,'Delta (AY.4-like)','V3',24),
  (7,1,'Delta (AY.4.2-like)','V3',1),
  (8,1,'Delta (B.1.617.2-like)','V3',2292),
  (9,1,'Delta (B.1.617.2-like)','V4.1',36),
  (10,1,'Delta (B.1.617.2-like) +K417N','V3',1),
  (11,1,'Delta (B.1.617.2-like) +K417N','V4.1',1),
  (12,1,'Epsilon (B.1.427-like)','V3',2),
  (13,1,'Epsilon (B.1.429-like)','V3',4),
  (14,1,'Eta (B.1.525-like)','V3',2),
  (15,1,'Gamma (P.1-like)','V3',58),
  (16,1,'Iota (B.1.526-like)','V3',230),
  (17,1,'Lambda (C.37-like)','V3',7),
  (18,1,'Mu (B.1.621-like)','V3',6),
  (19,1,'Omicron (BA.1-like)','V3',240),
  (20,1,'Omicron (BA.1-like)','V4.1',389),
  (21,1,'Omicron (BA.2-like)','V3',1),
  (22,1,'Omicron (BA.2-like)','V4.1',434),
  (23,1,'Omicron (BA.2-like)','V5.0-5.3.2_400',28),
  (24,1,'Omicron (BA.4-like)','V4.1',83),
  (25,1,'Omicron (BA.5-like)','V4.1',590),
  (26,1,'Omicron (XBB-like)','V4.1',7),
  (27,1,'Omicron (XBB-like)','V5.0-5.3.2_400',4),
  (28,1,'Omicron (XBB.1-like)','V4.1',28),
  (29,1,'Omicron (XBB.1-like)','V5.0-5.3.2_400',67),
  (30,1,'Omicron (XBB.1.16-like)','V4.1',9),
  (31,1,'Omicron (XBB.1.16-like)','V5.0-5.3.2_400',5),
  (32,1,'Omicron (XBB.1.5-like)','V4.1',169),
  (33,1,'Omicron (XBB.1.5-like)','V5.0-5.3.2_400',19),
  (34,1,'Omicron (XE-like)','V4.1',1),
  (35,1,'Zeta (P.2-like)','V3',1),
  (36,2,'.','V3',143),
  (37,2,'Alpha (B.1.1.7-like)','V3',328),
  (38,2,'Delta (B.1.617.2-like)','COVID-MIDNIGHT-1200',633),
  (39,2,'Delta (B.1.617.2-like)','V3',196),
  (40,2,'Delta (B.1.617.2-like)','V4.1',3),
  (41,2,'Delta (B.1.617.2-like) +K417N','V3',2),
  (42,2,'Epsilon (B.1.427-like)','V3',3),
  (43,2,'Epsilon (B.1.429-like)','V3',24),
  (44,2,'Omicron (BA.1-like)','COVID-MIDNIGHT-1200',269),
  (45,2,'Omicron (BA.2-like)','COVID-MIDNIGHT-1200',56),
  (46,2,'Omicron (BA.2-like)','V4.1',146),
  (47,2,'Omicron (BA.2-like)','V5.0-5.3.2_400',478),
  (48,2,'Omicron (BA.4-like)','V4.1',30),
  (49,2,'Omicron (BA.5-like)','V4.1',354),
  (50,2,'Omicron (XBB-like)','V5.0-5.3.2_400',3),
  (51,2,'Omicron (XBB.1-like)','V5.0-5.3.2_400',27),
  (52,2,'Omicron (XBB.1.16-like)','V5.0-5.3.2_400',7),
  (53,2,'Omicron (XBB.1.5-like)','V5.0-5.3.2_400',8);

